### ISSUE TITLE
Commands flags 

### ISSUE THREAD

**Issue by MatteoGabriele** [Blocklevel/blue-next#11]
### Goal
Use flags lunching commands to skip questions

### Description
This, for example, will create a new page with basic page setup directly
```bash
bcli page --name=home --basic
```
All questions that are not answered by flags, still need to be prompted

**Comment by floristenhove** [comment]
Or set sensible defaults for the other questions?

**Comment by MatteoGabriele** [comment]
@floristenhove all questions have already a default answer, so you can just press always `enter` and it goes automatically, but some questions need a text input

**Comment by floristenhove** [comment]
Awesome!

**Comment by MatteoGabriele** [comment]
see #50
