### ISSUE TITLE
Node async/await support

### ISSUE THREAD

**Issue by MatteoGabriele** [Blocklevel/blue-next#18]
Should we switch to the current version 7.7.0 to be able to use async/await functionalities?

**Comment by SoullessWaffle** [comment]
I would definitely be in favor of this if async/await was in an LTS release, but I'm not sure we want to build production projects on a non-LTS version of node.

We may want to wait for node v8 LTS to release and just keep using babel for async/await until then.
You can view the LTS schedule [here](https://github.com/nodejs/LTS#readme).

@jonaskuiler what do you think?

**Comment by MatteoGabriele** [comment]
@SoullessWaffle We should check if we are already not-LTS compatible actually. I should downgrade my node version to 6.4.0 and see what happen.

**Comment by ThaNarie** [comment]
If I may be so free, I think LTS support is only really needed for consumer-facing code that runs in production, so you know it's stable.
If you're building tooling it doesn't really matter _that_ much, and even transpiling your code with babel isn't that bad of a choice. Runtime performance is less of an issue for tooling.

Or am I missing something and is this about Server Side Rendering support in Blue? :)

**Comment by MatteoGabriele** [comment]
@ThaNarie The node version will be used to create new projects and also to run build and dev server, but is not something that will go in production: it's the actual tooling around.

So the main concern could be just running the build to a server that has an LTS and not the latest version of Node, but I guess this is not really a problem.

**Comment by MatteoGabriele** [comment]
For now we can leave the actual setup. 
If we want to switch to async/await it's probably better to have a compiled version of the all tool so we can support servers with the LTS version.
