### ISSUE TITLE
Add flowtype for opt-in static type checking

### ISSUE THREAD

**Issue by mickdekkers** [Blocklevel/blue-next#57]
https://flowtype.org

I'm working on a PR for this with @jonaskuiler's blessings, will update you with more information soon.

**Comment by SoullessWaffle** [comment]
Update: unfortunately, it seems that flow might not be a good fit for us in its present state.
I've compiled a list of issues I've encountered while attempting to integrate flow into blue-next: https://gist.github.com/SoullessWaffle/69fb27eaa0b780c84b5b2055d9cf6216

/cc @jonaskuiler @MatteoGabriele

**Comment by MatteoGabriele** [comment]
I will close this ticket for now, we might want to check later on when the library will get better integrated
