### ISSUE TITLE
Route is ignored on refresh

### ISSUE THREAD

**Issue by jonaskuiler** [Blocklevel/blue-next#72]
In a typical setup with some routes, deeplinking to a certain path will not work (e.g. /home) because the route is ignored. The "router/ROUTE_CHANGED" event is also not fired. This is due to the incorrect use of vue-router-sync. This should be called in the file where your router is attached to the application shell. 

Currently the vue-router-sync is imported in the file where the router instance is created. The Vuex store is also imported in there to tie both of them together. This is not needed because the bootstrap file also has access to both the router and the store.

I will create a pull request which resolves this issue.

**Comment by MatteoGabriele** [comment]
fixed with #73
