### ISSUE TITLE
add semi colons requirement to eslinter 

### ISSUE THREAD

**Issue by mientjan** [Blocklevel/blue-next#75]
add semi columns requirement to eslinter.

Removing semi colons ";" as a requirement from the eslinter is a bad and dangerous.

this will not do what you are expecting without semi colons. You expect it to execute foo and return its result to x. And expect a array to be multiplied by it self and return a new array.
```
const x = foo()
[0, 1, 2, 3, 4, 5].map(x => x*x)
```
Thats not what is happening here if you remove semi colons.

This is what actually happens.
```
const x = foo()[(0, 1, 2, 3, 4, 5)].map(x => x*x);
```

Removing semi colons as a requirement is bad.

**Comment by ThaNarie** [comment]
Extra context; google for "automatic semicolon insertion"

**Comment by ThaNarie** [comment]
Btw, this is how 'standard' feels about this topic:
https://github.com/feross/standard/blob/master/RULES.md#semicolons

**Comment by MatteoGabriele** [comment]
@mientjan the only scenario where you might have trouble with semicolons is that one 

```js
const x = foo()
[0, 1, 2, 3, 4, 5].map(x => x*x)
```
but to be honest: 
1) this example doesn't make any sense
2) linter will suggest to add a semicolon
3) just assign the map to a variable ( which make sense )
4) avoiding semicolons is part of the standard of eslint standard javascript plugin

I don't say that semicolons are bad: we just decided to go with standards and not use them and we **never** had any kind of issues.
