### ISSUE TITLE
Let start script optionally take port as command line argument

### ISSUE THREAD

**Issue by mickdekkers** [Blocklevel/blue-next#99]
I would like to use [Hotel](https://github.com/typicode/hotel) to manage my dev servers, but it needs to be able to pass a port to the `blue-scripts` `start` script, e.g. `blue-scripts start --port 3030`

The `start` script currently always uses `portfinder` to find an available port.
Instead, I suggest using this behavior:

- If the port is in `argv`, use that port. If the port is taken or an error occurs, stop the script and don't look for a different port.
- If it's not in `argv`, use the current `portfinder` behavior to find a port.

@MatteoGabriele does this sound reasonable?

**Comment by MatteoGabriele** [comment]
you can already add a fixed port since blue-script@1.7.0

add a `port` property in the blue.config.js file like so

```js
module.exports = {
   name: 'my-project',
   port: 8081
}
```
